# Generated by Django 3.1.2 on 2021-01-07 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("emojified_tweets_wall_of_fame", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="posted_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        )
    ]
