# Generated by Django 3.1.5 on 2021-01-10 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("emojified_tweets_wall_of_fame", "0002_customusertotweet")]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="posted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
